version: 1
runtime: python 27
api_version: 1
threadsafe: true
application: autocomplete

handlers:
- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets

- url: handlers
  script: routing.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
